name: zefeffete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
    - assets/vendor1.jpg
    - assets/vendor2.jpg
    - assets/vendor3.jpg
    - assets/venue1.jpg
    - assets/venue2.jpg
    - assets/venue3.jpg
    - assets/startingPage1.jpg
    - assets/startingPage2.jpg
    - assets/startingPage3.jpg
