name: wedding_organizer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/flowers1.png
    - lib/assets/images/flowers2.png
    - lib/assets/images/aliance.png
    - lib/assets/images/profilepic.png
    - lib/assets/images/algeria_flag.jpg



